op = require('./GeometryCalculator.js')
console.log("Cube Volume is:", op.cubevolume(3))
console.log("Cube Surface Area is:", op.surface_area_of_cube(3))
console.log("Volume of cuboid:", op.cuboidvolume(3,4,5))
console.log("Surface area of cuboid:", op.cuboid_surface_area(3,4,5))
console.log("Volume of sphere:", op.spherevolume(3))
console.log("Surface area of cylinder:", op.cylinder_surface_area(3,2))
console.log("Volume of Cone:", op.conevolume(3,4))
console.log("Surface Area of Cone:", op.cone_surface_area(3,4))
console.log("Volume of pyramid:", op.pyramidvolume(4,5))
console.log("SUraface Area of pyramid:", op.pyramid_surface_area(7,4,5))
console.log("Volume of ellipsoid:", op.ellipsoidvolume(7,4,5))
console.log("Surface Area of ellipsoid:", op.ellipsoid_surface_area(7,4,5))